print ("nombre completo -Reyna yamile calzada campos")
print ("lugar de residencia - emiliano zapata")
print ("fecha de nacimiento - 28 de diciembre del 2003")
print ("color favorito - rosa")
print ("animal- los pajaros")
print ("que esla programacion - la programacion es un proceso al que se recurre para crear algun tipo de aplicacion o software , tambien requiere la utilizacion de lenguaje informatico para poder llevar acabo una solucion de un problema")
print ("porque es importante la programacion - la programacion es importante ya que es una herramienta muy fundamental para el avance de la tegnologia dentro de la industria  y en el ambito laboral y nos ayuda a resolver problemas  mediante codigos")
print ("la herencia -la herencia nos permite definir nuevas clases basadas de unos objetos ya existente y tambien tiene elementos comunes")
print ("pliformismo - el poliformismo es una propiedad por lo que es posible enviar un mensaje y tambien los objetos tienen la misma accion pero son objetos diferentes")
print ("abtraccion - la abtraccion consiste en aislar un elemento de su contexto de los elementos que lo acompañan")
print ("encapsulamiento -el encapsulamiento es una funcion que oculta su funcion y nadien la puede ver")
